#!/usr/bin/env python

from parser import pcapToMatrix
from dataEvaluation import dataEval

trainingPcap = '/home/cb/Desktop/training.pcap'
slammerPcap = '/home/cb/Desktop/slammer.pcap'
manInTheMiddlePcap = '/home/cb/Desktop/manInTheMiddle.pcap'
largePcap = '/home/cb/Desktop/large.pcap'
dnsPcap = '/home/cb/Desktop/dns-remoteshell.pcap'

dataEval(trainingPcap, manInTheMiddlePcap)
dataEval(trainingPcap, dnsPcap)
#dataEval(trainingPcap, slammerPcap)
dataEval(trainingPcap, largePcap)